tiledlayout(2,2);
nexttile([1,2]);
T=readtable("附件1：物流网络历史货量数据.xlsx","VariableNamingRule","preserve");
x=T(strcmp(T.("场地1"),"DC14"),:);
y=x(strcmp(x.("场地2"),"DC10"),:);
bar(y.("货量"));
set(gca,"YScale","log" );
title("DC14-DC10");
nexttile([1,2]);
x=T(strcmp(T.("场地1"),"DC20"),:);
y=x(strcmp(x.("场地2"),"DC35"),:);
bar(y.("货量"));
set(gca,"YScale","log" );
title("DC20-DC35");